---
- name: Configure the Oracle APT key
  become: yes
  become_method: sudo
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: Configure the VirtualBox APT repositories
  become: yes
  become_method: sudo
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

- name: Install VirtualBox
  become: yes
  become_method: sudo
  apt: pkg=virtualbox-{{ virtualbox_version }} state=present update_cache=yes
 
- name: Download Virtualbox extpack
  become: yes
  become_method: sudo
  get_url: url=http://download.virtualbox.org/virtualbox/{{ virtualbox_extension_pack_version.split('-')[0] }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extension_pack_version }}.vbox-extpack dest=/tmp mode=0644

- name: Install Virtualbox extpack  
  become: yes
  become_method: sudo
  command: vboxmanage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extension_pack_version }}.vbox-extpack creates=/usr/lib/virtualbox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack

- name: remove vboxnet0 
  become: yes
  become_method: sudo
  command: vboxmanage hostonlyif remove vboxnet0
  ignore_errors: true

- name: remove vboxnet1 
  become: yes
  become_method: sudo
  command: vboxmanage hostonlyif remove vboxnet1
  ignore_errors: true

- name: Create vboxnet0
  become: yes
  become_method: sudo
  command: vboxmanage hostonlyif create

- name: Create vboxnet1
  become: yes
  become_method: sudo
  command: vboxmanage hostonlyif create

- name: Turn up vboxnet0
  become: yes
  become_method: sudo
  command: ifconfig vboxnet0 up

- name: Configure vboxnet0 
  become: yes
  become_method: sudo
  command: ifconfig vboxnet0 192.168.56.1 netmask 255.255.255.0 broadcast 192.168.56.1

- name: Turn up vboxnet1 
  become: yes
  become_method: sudo
  command: ifconfig vboxnet1 up

- name: Configure vboxnet1 
  become: yes
  become_method: sudo
  command: ifconfig vboxnet1 192.168.57.1 netmask 255.255.255.0 broadcast 192.168.57.1
